# Generated by Django 4.1.4 on 2023-01-01 00:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_teacher_customuser_birthday_customuser_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="birthday",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 1, 1, 0, 12, 29, 255996),
                verbose_name="birthday",
            ),
        ),
    ]
