# Generated by Django 4.1.4 on 2023-01-02 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_customuser_birthday"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teacher",
            options={
                "managed": True,
                "verbose_name": "Teacher",
                "verbose_name_plural": "Teachers",
            },
        ),
        migrations.AlterField(
            model_name="customuser",
            name="birthday",
            field=models.DateTimeField(verbose_name="birthday"),
        ),
    ]
